spring.application.name=extractTransaction Application
# Enable multipart uploads
spring.servlet.multipart.enabled=true

# Maximum file size
spring.servlet.multipart.max-file-size=5MB

# Maximum request size
spring.servlet.multipart.max-request-size=5MB

logging.level.org.springframework=INFO
logging.level.com.example=DEBUG
file.upload=C:\\Users\\vishn\\OneDrive\\Desktop\\TransactionFile

spring.datasource.url=jdbc:postgresql://localhost:5432/BankStatement
spring.datasource.username=postgres
spring.datasource.password=vishnu@2002
spring.datasource.driver-class-name=org.postgresql.Driver